name: PR Build

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: |
          17
        distribution: 'zulu'
        cache: 'gradle'
    - name: Build
      run: ./gradlew -PenableCrossCompilerPlugin=true build
